add: common entity
Yapp-17th/Android_2_Backend pull request #2
Opened 2020-09-20 09:00 UTC by sypark9646

흠... 테스트 해보려고 했는데 ddl-auto를 줬는데도 테이블 자동생성이 안 되네요ㅠㅠ
그리고 https://docs.google.com/spreadsheets/d/1rcqHECLazic8Pxhcf-EFFji0uVePV2BC1Ndm2lTm0hY/edit#gid=1629621718에 필드 추가해야할 것 같은 부분 빨간색으로 표시해놨는데 시간 나실 때 한 번만 봐주실 수 있나요?

2020-09-20 11:23 UTC, dnjscksdn98 requested changes

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  @GeneratedValue
```suggestion
  @GeneratedValue(strategy = GenerationType.IDENTITY)
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private long id;
```suggestion
  private Long id;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private int reportPoints = 0;
저는 Wrapper 클래스(ex: Integer)를 선호하는 편이긴 하지만,
Primitive 타입을 사용한다면 int 의 디폴트 값은 0 이므로 뒤에 0으로 초기화 시킨 것은 빼도 될것 같네요.

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Address.java
> +  @GeneratedValue
```suggestion
  @GeneratedValue(strategy = GenerationType.IDENTITY)
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Address.java
> +  private LocalDateTime updatedAt;
```suggestion
  @UpdateTimestamp
  private LocalDateTime updatedAt;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Address.java
> +  @OneToOne(fetch = FetchType.LAZY)
하나의 주소(address)가 여러 사용자(user)들한테 부여할 수 있는데,
그렇다면 ```OneToMany``` 로 하는게 맞지 않을까요?

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/resources/application.yml
> +        format_sql: true
개행(newline)이 필요합니다.

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  @OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
여러 사용자(user)들이 하나의 주소(address)에 매핑할 수 있으니깐 ```ManyToOne``` 이 더 맞을 것 같네요.

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Category.java
> +  private long id;
```suggestion
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Category.java
> +  private User user;
하나의 category 가 여러 사용자(user) 들한테 매핑될 수 있으므로 ```OneToMany```가 맞을 것 같네요.
```suggestion
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
  private List<User> users = new ArrayList<>();
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  @OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
```suggestion
  @ManyToOne(fetch = FetchType.LAZY)
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Address.java
> +  private User user;
```suggestion
  @ManyToOne(fetch = FetchType.LAZY, mappedBy = "user")
  private List<User> users = new ArrayList<>();
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private Category categoty;
여러 사용자(user)가 하나의 category에 매핑될 수 있으므로 ```ManyToOne```이 맞을 것 같네요.
중간에 오타도 있네요.(categoty -> category)
```suggestion
  @ManyToOne(fetch = FetchType.LAZY)
  private Category category;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Tag.java
> +  private long id;
```suggestion
  @Id
  @GeneratedValue(strategy = = GenerationType.IDENTITY)
  private Long id;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Tag.java
> +  private User user;
하나의 tag 가 여러 사용자(user)들한테 매핑할 수 있으므로 ```OneToMany```가 맞을 것 같네요.
```suggestion
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
  private List<User> users = new ArrayList<>();
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Tag.java
> +  private LocalDateTime updatedAt;
```suggestion
  @UpdateTimestamp
  private LocalDateTime updatedAt;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Tag.java
> +  private List<Board> members = new ArrayList<>();
Board 엔티티에 있는 ```tag``` 를 매핑해줘야 하므로 ```mappedBy``` 추가해주시고,
변수 네이밍도 ```members``` 가 아니라 ```boards``` 가 괜찮을 거 같네요.
```suggestion
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "tag")
  private List<Board> boards = new ArrayList<>();
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private Tag tag;
여러 사용자가 하나의 태그에 매핑할 수 있으므로 ```ManyToOne``` 이 맞을 것 같네요.
```suggestion
  @ManyToOne(fetch = FetchType.LAZY)
  private Tag tag;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private List<Board> members = new ArrayList<>();
변수 네이밍을 ```members``` 보다 ```boards```가 더 적합할 거 같네요.
```suggestion
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
  private List<Board> boards = new ArrayList<>();
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/BookMark.java
> +}
생각을 해보니깐 BookMark 엔티티를 추가하지 말고
사용자(user) 엔티티에 ```List<Board> bookmarks = new ArrayList<>();``` 를 사용하면 될 것 같네요.

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Category.java
> +  private LocalDateTime updatedAt;
```suggestion
  @UpdateTimestamp
  private LocalDateTime updatedAt;
```

2020-09-20 11:23 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/Category.java
> +  private List<Board> members = new ArrayList<>();
```OneToMany```는 ```mappedBy```를 설정해줘야 합니다.
변수 네이밍도 ```boards``` 가 더 괜찮을 것 같네요.
```suggestion
  @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
  private List<Board> boards = new ArrayList<>();
```

2020-09-20 11:25 UTC, dnjscksdn98 commented
그리고 모든 파일에 개행(newline)이 필요합니다. 필수 사항은 아니지만 가끔 배포나 추후에 문제가 발생할 수 있어요.
https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file
이거 참고하시면 될 것 같아요.

2020-09-20 11:27 UTC, dnjscksdn98 commented
지금 다 보진 못했지만 수정해야될게 많아서 제가 cleanup 브랜치 파서 바로 수정하고 다시 pull request 생성해서 다시 한번 리뷰해보죠.

2020-09-20 11:28 UTC, sypark9646 commented on common-module/src/main/java/domain/model/User.java
> +  @GeneratedValue
아하 디폴트가 AUTO군요

2020-09-20 11:33 UTC, sypark9646 commented on common-module/src/main/java/domain/model/User.java
> +  private int reportPoints = 0;
음 전 생각없이 쓰긴 했는데, 찾아보니까 warpper class 장점이
* Unboxing을 하지 않으면 산술 연산이 불가능 하지만, null 값을 처리할 수 있다. 
* null 값 처리가 용이하기 때문에 SQL과 연동할 경우 처리가 용이하다.
* DB에서 자료형이 정수형이지만 null 값이 필요한 경우 VO에서 Integer를 사용할 수 있음.

nullable인 경우는 wrapper class를 써야하는구나...

혹시 그러면 NOT NULL constraint가 있는 경우는 primitive를 쓰고 아닐 경우에는 래퍼 클래스를 쓰는 경우는 너무 복잡하겠죠?? 그렇다면 아예 wrapper클래스를 쓰는걸로 통일하는 편이 더 좋을 것 같기도 하네요...!

2020-09-20 11:35 UTC, dnjscksdn98 commented
지금 전체적으로 ```OneToMany```와 ```ManyToOne```을 조금 헷갈려 하시는 것 같네요.

2020-09-20 11:35 UTC, sypark9646 commented on common-module/src/main/java/domain/model/User.java
> +  private long id;
https://stackoverflow.com/questions/3535791/primitive-or-wrapper-for-hibernate-primary-keys 참고

2020-09-20 11:39 UTC, sypark9646 commented on common-module/src/main/java/domain/model/Address.java
> +  private LocalDateTime updatedAt;
@CreationTimestamp: INSERT시에 현재 시간을 읽어서 저장
@UpdateTimestamp: UPDATE시에 현재 시간을 읽어서 저장

2020-09-20 11:39 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private int reportPoints = 0;
넵넵 좋아요

2020-09-20 11:47 UTC, sypark9646 commented on common-module/src/main/java/domain/model/BookMark.java
> +}
@dnjscksdn98 앗 저는 User와 Board가 many to many 관계라 이걸 many to one + one to may 이런 식으로 쪼개려고 하신 줄 알았는데 아니었나요??

2020-09-20 12:01 UTC, dnjscksdn98 requested changes

2020-09-20 12:01 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private List<BookMark> bookMarks = new ArrayList<>();
Bookmark 엔티티는 삭제해주시고 이런식으로 하면 될것 같아요.
```suggestion
  @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
  private List<Board> bookMarks = new ArrayList<>();
```

2020-09-20 12:01 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/User.java
> +  private List<Message> messages = new ArrayList<>();
채팅방만 가지고 있으면 될 것 같아요.
채팅을 조회할 경우에는 해당 채팅방에 저장된 채팅 메시지를 조회하는 쪽으로 하죠.

2020-09-20 12:06 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/BookMark.java
> +}
이거 BookMark 엔티티는 필요없을 것 같아요.
```List<Board> bookmarks = new ArrayList<>()``` 이 형태로 가는게 맞을 것 같아요.

2020-09-20 12:21 UTC, sypark9646 commented on common-module/src/main/java/domain/model/BookMark.java
> +}
아하 같은 글을 여러 번 북마크 하지 않으니까 그런 건가,,, 뭔가 이해될 것 같기도 하네요

2020-09-20 12:45 UTC, dnjscksdn98 commented on common-module/src/main/java/domain/model/BookMark.java
> +}
지금 ```user``` 와 ```board``` 두개의 연관관계가 잡혀 있어서 데이터베이스에 추가를 하거나 삭제를 할때 코드가 엄청 꼬일거에요 이대로 간다면.
예를 들면 북마크 추가 로직을 작성한다면

변경 전 User.java

```java
public void addBookMark(Board board, User user) {
    BookMark bookMark = new BookMark(user, board);
    bookMarks.add(bookMark);
}
```

변경 후 User.java

```java
public void addBookMark(Board board) {
    bookMarks.add(board);
}
```

즉, 게시글(board) 자체만으로도 구현가능한데 불필요한 엔티티를 추가해서 자원을 낭비하게 되는 거죠.

2020-09-20 12:54 UTC, dnjscksdn98 commented on common-module/src/main/resources/application.yml
> +    database-platform: mysql
mysql 5.xx 버전을 사용중이라면 아래처럼 작성해보시고, 8.xx 버전이시면 아래에 5를 8로 수정후 한번 해보세요.
그래도 ddl-auto: create가 안되신다면 개발에는 h2 데이터베이스(디폴트값 = create)가 효율적이니깐 한번 해보시면 될것 같네요.
```suggestion
    database-platform: org.hibernate.dialect.MySQL5Dialect
```

2020-09-20 12:55 UTC, dnjscksdn98 commented on common-module/src/main/resources/application.yml
> +    database-platform: mysql
아니면 resource 디렉터리에 init.sql 하나 생성해서 직접 쿼리 작성해도 될거에요.

2020-09-20 16:43 UTC, sypark9646 commented on common-module/src/main/java/domain/model/User.java
> +  private Tag tag;
다시 보니까 즐겜러는 유저 소개에 쓰는 것이 아니라 게시물에만 쓰네요. 이 부분은 지우도록 하겠습니다

2020-09-25 07:30 UTC, dnjscksdn98 approved these changes

2020-09-25 07:31 UTC, merged